### ISSUE TITLE
Destroy issue

### ISSUE THREAD

**Issue by paigerube14** [openshift-qe/ocp-qe-perfscale-ci#86]
Currently there is an error that gets thrown when install fails and it goes and automatically calls destroy. Seems like the build number is not being found properly

```
02-22 15:24:15.611  java.lang.NumberFormatException: For input string: ""
02-22 15:24:15.611  	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
02-22 15:24:15.611  	at java.lang.Integer.parseInt(Integer.java:592)
02-22 15:24:15.611  	at java.lang.Integer.parseInt(Integer.java:615)
02-22 15:24:15.611  	at hudson.plugins.copyartifact.SpecificBuildSelector.getBuild(SpecificBuildSelector.java:70)
02-22 15:24:15.611  	at hudson.plugins.copyartifact.CopyArtifact.perform(CopyArtifact.java:454)
02-22 15:24:15.611  	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
02-22 15:24:15.611  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:100)
02-22 15:24:15.611  	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:70)
02-22 15:24:15.611  	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
02-22 15:24:15.611  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
02-22 15:24:15.611  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
02-22 15:24:15.611  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
02-22 15:24:15.611  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
02-22 15:24:15.611  	at java.lang.Thread.run(Thread.java:750)
02-22 15:24:15.622  Finished: FAILURE
```

**Comment by paigerube14** [comment]
This issue was because of an issue on my branch while I was adding vsphere support. 

I fixed it with this PR to my branch https://github.com/paigerube14/ocp-qe-perfscale-ci/pull/1
